apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: h2o-operator
  namespace: domino-compute
# TODO: Figure out exact priveledges needed.
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apps.dominodatalab.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: h2o-operator
  namespace: domino-platform
# TODO: Figure out exact priveledges needed.
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
