apiVersion: v1
kind: ServiceAccount
metadata:
  name: h2o-user
  namespace: domino-compute
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: domino-compute
  name: h2o-user
rules:
- apiGroups: ["apps.dominodatalab.com"] 
  resources: ["h2oclusters"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: h2o-user
  namespace: domino-compute
subjects:
- kind: ServiceAccount
  name: h2o-user
  namespace: domino-compute
roleRef:
  kind: Role
  name: h2o-user
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: h2o-user
  namespace: domino-compute
  annotations:
    kubernetes.io/service-account.name: h2o-user
type: kubernetes.io/service-account-token
