apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
{{ include "chart.labels" . | indent 4 }}
  name: h2o-{{ .Values.runId }}-driver
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: node
          app.kubernetes.io/instance: h2o-{{ .Values.runId }}
          app.kubernetes.io/name: {{ include "chart.name" . }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: run-{{ .Values.runId }}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
{{ include "chart.labels" . | indent 4 }}
  name: h2o-{{ .Values.runId }}-node
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          domino-platform: "true"
      podSelector:
        matchLabels:
          h2o-ui-client: "true"
    ports:
    - port: 54321
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: node
          app.kubernetes.io/instance: h2o-{{ .Values.runId }}
          app.kubernetes.io/name: {{ include "chart.name" . }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: run-{{ .Values.runId }}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/instance: h2o-{{ .Values.runId }}
      app.kubernetes.io/name: {{ include "chart.name" . }}
  policyTypes:
  - Ingress
