apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: h2o-{{ .Values.runId }}
    app.kubernetes.io/name: {{ include "chart.name" . }}
  ports:
  - protocol: TCP
    port: 54321 
    targetPort: 54321
    name: http
